module Evergreen.Migrate.V9 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V3.Main
import Evergreen.V3.Main.Pages.Model
import Evergreen.V3.Main.Pages.Msg
import Evergreen.V3.Pages.Home_
import Evergreen.V3.Pages.NotFound_
import Evergreen.V3.Pages.Spelling
import Evergreen.V3.Shared
import Evergreen.V3.Shared.Model
import Evergreen.V3.Shared.Msg
import Evergreen.V3.Types
import Evergreen.V9.Main
import Evergreen.V9.Main.Pages.Model
import Evergreen.V9.Main.Pages.Msg
import Evergreen.V9.Pages.Home_
import Evergreen.V9.Pages.NotFound_
import Evergreen.V9.Pages.Spelling
import Evergreen.V9.Shared
import Evergreen.V9.Shared.Model
import Evergreen.V9.Shared.Msg
import Evergreen.V9.Types
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V3.Types.FrontendModel -> ModelMigration Evergreen.V9.Types.FrontendModel Evergreen.V9.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V3.Types.BackendModel -> ModelMigration Evergreen.V9.Types.BackendModel Evergreen.V9.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V3.Types.FrontendMsg -> MsgMigration Evergreen.V9.Types.FrontendMsg Evergreen.V9.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V3.Types.ToBackend -> MsgMigration Evergreen.V9.Types.ToBackend Evergreen.V9.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V3.Types.BackendMsg -> MsgMigration Evergreen.V9.Types.BackendMsg Evergreen.V9.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V3.Types.ToFrontend -> MsgMigration Evergreen.V9.Types.ToFrontend Evergreen.V9.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V3.Types.FrontendModel -> Evergreen.V9.Types.FrontendModel
migrate_Types_FrontendModel old =
    old |> migrate_Main_Model


migrate_Types_FrontendMsg : Evergreen.V3.Types.FrontendMsg -> Evergreen.V9.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    old |> migrate_Main_Msg


migrate_Main_Model : Evergreen.V3.Main.Model -> Evergreen.V9.Main.Model
migrate_Main_Model old =
    { key = old.key
    , url = old.url
    , page = old.page |> migrate_Main_Pages_Model_Model
    , layout = old.layout
    , shared = old.shared |> migrate_Shared_Model
    }


migrate_Main_Msg : Evergreen.V3.Main.Msg -> Evergreen.V9.Main.Msg
migrate_Main_Msg old =
    case old of
        Evergreen.V3.Main.UrlRequested p0 ->
            Evergreen.V9.Main.UrlRequested p0

        Evergreen.V3.Main.UrlChanged p0 ->
            Evergreen.V9.Main.UrlChanged p0

        Evergreen.V3.Main.Page p0 ->
            Evergreen.V9.Main.Page (p0 |> migrate_Main_Pages_Msg_Msg)

        Evergreen.V3.Main.Layout p0 ->
            Evergreen.V9.Main.Layout p0

        Evergreen.V3.Main.Shared p0 ->
            Evergreen.V9.Main.Shared (p0 |> migrate_Shared_Msg)

        Evergreen.V3.Main.Batch p0 ->
            Evergreen.V9.Main.Batch (p0 |> List.map migrate_Main_Msg)


migrate_Main_Pages_Model_Model : Evergreen.V3.Main.Pages.Model.Model -> Evergreen.V9.Main.Pages.Model.Model
migrate_Main_Pages_Model_Model old =
    case old of
        Evergreen.V3.Main.Pages.Model.Home_ p0 ->
            Evergreen.V9.Main.Pages.Model.Home_ (p0 |> migrate_Pages_Home__Model)

        Evergreen.V3.Main.Pages.Model.Spelling p0 ->
            Evergreen.V9.Main.Pages.Model.Spelling (p0 |> migrate_Pages_Spelling_Model)

        Evergreen.V3.Main.Pages.Model.NotFound_ p0 ->
            Evergreen.V9.Main.Pages.Model.NotFound_ (p0 |> migrate_Pages_NotFound__Model)

        Evergreen.V3.Main.Pages.Model.Redirecting_ ->
            Evergreen.V9.Main.Pages.Model.Redirecting_

        Evergreen.V3.Main.Pages.Model.Loading_ ->
            Evergreen.V9.Main.Pages.Model.Loading_


migrate_Main_Pages_Msg_Msg : Evergreen.V3.Main.Pages.Msg.Msg -> Evergreen.V9.Main.Pages.Msg.Msg
migrate_Main_Pages_Msg_Msg old =
    case old of
        Evergreen.V3.Main.Pages.Msg.Home_ p0 ->
            Evergreen.V9.Main.Pages.Msg.Home_ (p0 |> migrate_Pages_Home__Msg)

        Evergreen.V3.Main.Pages.Msg.Spelling p0 ->
            Evergreen.V9.Main.Pages.Msg.Spelling (p0 |> migrate_Pages_Spelling_Msg)

        Evergreen.V3.Main.Pages.Msg.NotFound_ p0 ->
            Evergreen.V9.Main.Pages.Msg.NotFound_ (p0 |> migrate_Pages_NotFound__Msg)


migrate_Pages_Home__Model : Evergreen.V3.Pages.Home_.Model -> Evergreen.V9.Pages.Home_.Model
migrate_Pages_Home__Model old =
    old


migrate_Pages_Home__Msg : Evergreen.V3.Pages.Home_.Msg -> Evergreen.V9.Pages.Home_.Msg
migrate_Pages_Home__Msg old =
    case old of
        Evergreen.V3.Pages.Home_.SmashedLikeButton ->
            Evergreen.V9.Pages.Home_.SmashedLikeButton


migrate_Pages_NotFound__Model : Evergreen.V3.Pages.NotFound_.Model -> Evergreen.V9.Pages.NotFound_.Model
migrate_Pages_NotFound__Model old =
    old


migrate_Pages_NotFound__Msg : Evergreen.V3.Pages.NotFound_.Msg -> Evergreen.V9.Pages.NotFound_.Msg
migrate_Pages_NotFound__Msg old =
    case old of
        Evergreen.V3.Pages.NotFound_.NoOp ->
            Evergreen.V9.Pages.NotFound_.NoOp


migrate_Pages_Spelling_Model : Evergreen.V3.Pages.Spelling.Model -> Evergreen.V9.Pages.Spelling.Model
migrate_Pages_Spelling_Model old =
    { state = old.state |> migrate_Pages_Spelling_State
    , actual = old.actual
    , expected = old.expected |> migrate_Pages_Spelling_Word
    , remaining = old.remaining |> List.map migrate_Pages_Spelling_Word
    , gifs_random_index = old.gifs_random_index
    }


migrate_Pages_Spelling_Msg : Evergreen.V3.Pages.Spelling.Msg -> Evergreen.V9.Pages.Spelling.Msg
migrate_Pages_Spelling_Msg old =
    case old of
        Evergreen.V3.Pages.Spelling.KeyInput p0 ->
            Evergreen.V9.Pages.Spelling.KeyInput p0

        Evergreen.V3.Pages.Spelling.ButtonRepeat ->
            Evergreen.V9.Pages.Spelling.ButtonRepeat

        Evergreen.V3.Pages.Spelling.ButtonNext ->
            Evergreen.V9.Pages.Spelling.ButtonNext

        Evergreen.V3.Pages.Spelling.RandomNumber p0 ->
            Evergreen.V9.Pages.Spelling.RandomNumber p0

        Evergreen.V3.Pages.Spelling.Focus p0 ->
            Evergreen.V9.Pages.Spelling.Focus p0


migrate_Pages_Spelling_State : Evergreen.V3.Pages.Spelling.State -> Evergreen.V9.Pages.Spelling.State
migrate_Pages_Spelling_State old =
    case old of
        Evergreen.V3.Pages.Spelling.Playing ->
            Evergreen.V9.Pages.Spelling.Playing

        Evergreen.V3.Pages.Spelling.Finished ->
            Evergreen.V9.Pages.Spelling.Finished


migrate_Pages_Spelling_Word : Evergreen.V3.Pages.Spelling.Word -> Evergreen.V9.Pages.Spelling.Word
migrate_Pages_Spelling_Word old =
    case old of
        Evergreen.V3.Pages.Spelling.Short ->
            ModelReset

        Evergreen.V3.Pages.Spelling.Born ->
            ModelReset

        Evergreen.V3.Pages.Spelling.Horse ->
            ModelReset

        Evergreen.V3.Pages.Spelling.More ->
            ModelReset

        Evergreen.V3.Pages.Spelling.Before ->
            ModelReset

        Evergreen.V3.Pages.Spelling.Morning ->
            ModelReset

        Evergreen.V3.Pages.Spelling.Score ->
            ModelReset

        Evergreen.V3.Pages.Spelling.Door ->
            ModelReset

        Evergreen.V3.Pages.Spelling.Wore ->
            ModelReset

        Evergreen.V3.Pages.Spelling.Shore ->
            ModelReset


migrate_Shared_Model : Evergreen.V3.Shared.Model -> Evergreen.V9.Shared.Model
migrate_Shared_Model old =
    old |> migrate_Shared_Model_Model


migrate_Shared_Model_Model : Evergreen.V3.Shared.Model.Model -> Evergreen.V9.Shared.Model.Model
migrate_Shared_Model_Model old =
    old


migrate_Shared_Msg : Evergreen.V3.Shared.Msg -> Evergreen.V9.Shared.Msg
migrate_Shared_Msg old =
    old |> migrate_Shared_Msg_Msg


migrate_Shared_Msg_Msg : Evergreen.V3.Shared.Msg.Msg -> Evergreen.V9.Shared.Msg.Msg
migrate_Shared_Msg_Msg old =
    case old of
        Evergreen.V3.Shared.Msg.GotNewSmashedLikes p0 ->
            Evergreen.V9.Shared.Msg.GotNewSmashedLikes p0
